#!/bin/bash

BASE_DIR=$(pwd)

read -p " На данном сервере установка производится впервые? (y/n): "

if [[ "$REPLY" =~ ^[yn]$ ]]; then
	if [[ "$REPLY" == "y" ]]; then

		apt-get update
		apt-get upgrade
		apt-get install python3 python3-pip
		python3 -m pip install --upgrade pip
		pip3 install virtualenv
		apt-get install libpq-dev 
		apt-get install postgresql postgresql-contrib 
		pip install psycopg2
		pip install uwsgi
		apt-get install nginx
		/etc/init.d/nginx start 
		cp emperor.uwsgi.service /etc/systemd/system/.
		sudo snap install core; sudo snap refresh core
		snap install --classic certbot
		ln -s /snap/bin/certbot /usr/bin/certbot
		./seconds.sh
	else
		./seconds.sh
	fi

	
else
	echo " Неверный ввод "


fi


